title: "VidarDB"
address: www.vidardb.com # site url
repo: github.com/vidardb
comments: false

exclude: ["vendor", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.txt", "Rakefile", "_drafts"]
plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-babel
  - jekyll-github-metadata
  - bourbon
  - neat

source: ./
destination: ./_site
sass:
  sass_dir: _sass

# Blog settings
paginate: 5
paginate_file: blog/index.html
paginate_path: /blog/page:num
permalink: /blog/:title
excerpt_separator: <!--more-->

markdown    : kramdown
highlighter : rouge

# Author settings
author:
  name : "soarpenguin"

# social settings
og_locale: "en_US"


